stages:
  - build
  - test

build:
  stage: build
  image: node
  only: 
    - master
  script: 
    - echo "Start building App"
    - npm install
    - npm run build
    - echo "Build successfully!"
  artifacts:
    expire_in: 1 hour      
    paths:
      - build
      - node_modules/

test:
  stage: test
  image: node
  only: 
    - master
  script:
    - echo "Testing App"
    - CI=true npm run test
    - echo "Test successfully!"
